services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  qdrant:
      image: qdrant/qdrant
      ports:
        - 6333:6333
        - 6334:6334
      volumes:
        - qdrant:/qdrant/storage
volumes:
  pgdata:
  qdrant:
